apiVersion: apps/v1
kind: Deployment
metadata:
  name: observe-opentelemetry-collector
spec:
  template:
    spec:
      containers:
        - name: observe-traces
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
